### ISSUE TITLE
Support Multiple Requests

### ISSUE THREAD

**Issue by jaruba** [Stremio/stremio-aggregators#5]
Proposing a `requestAgain` header or property that asks Stremio to request more streams from the add-on.

Extremely useful in cases where an add-on is waiting for multiple responses itself, and right now it would need to wait for all of it's requests in order to answer with stream results.

This can make a big difference in how long users wait for results from it.

`requestAgain` should have some sort of a limit, like 20 requests to avoid DDOS or error prone scenarios.

We should also think of how to make it respect order at the end, in cases where the add-on orders the responses from all of it's requests.

Maybe the best way to do this is for the add-on to always respond with all of it's streams, not just the new streams from the last request, and Stremio should always overwrite it's previous add-on results with the new ones, thus respecting the new stream order.

**Comment by Ivshti** [comment]
I'd say it needs to be a property, cause it needs to be transport-agnostic; stremio-addon-client already abstracts over the transport, and this is literarily a job of the aggregators

if it's implemented in the aggregators, it's kind of clean and I can't say anything bad about it

should it only be for streams or also for other types of content?

**Comment by Ivshti** [comment]
because we practically destroyed the usecase for this in a convo with @jaruba, I'm closing this
